# Generated by Django 5.1.2 on 2024-11-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("card_id", models.IntegerField(primary_key=True, serialize=False)),
                ("password", models.IntegerField(max_length=128)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
