# Generated by Django 5.1.2 on 2024-11-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
